# btw. It's suppoused to build the thing in like the thing. Not take bin from repo

name=randix
version=1.0.0
SRC_URL="https://github.com/Sqydev/randix/archive/refs/tags/v\${version}.tar.gz"
release=1
build_style="makefile"
make_build_target="release"
make_install_args="PREFIX=/usr"
summary="Matrix effect but the characters are all over the screen"
license="GPL-3.0-or-later"
url="https://github.com/Sqydev/randix"
maintainer="Sqyd <138494523+Sqydev@users.noreply.github.com>"
arch="*"
dependencies=""
