name=randix
version=1.0.0
release=1
summary="A simple terminal program that displays random characters."
license="GPL3"
url="https://github.com/Sqydev/randix"
maintainer="Sqyd"
arch=x86_64
dependencies=""
